### ISSUE TITLE
他的占用似乎比qq本身要大，所以他可能并不适合某些人

### ISSUE THREAD

**Issue by hulu976** [insoxin/QQScreenShot#15]
<img width="579" alt="屏幕截图 2024-01" src="https://github.com/insoxin/QQScreenShot/assets/157809096/872269f3-0a3e-4f0b-84b6-d52d89e492b5">

**Comment by insoxin** [comment]
![image](https://github.com/user-attachments/assets/8db2b897-16e7-42a4-9b4b-66460084bd6b)
