### ISSUE TITLE
Win11似乎无法使用，一点击启动就闪退

### ISSUE THREAD

**Issue by qingyao-code** [insoxin/QQScreenShot#18]

**Comment by huahangc** [comment]
兼容模式启动

**Comment by qingyao-code** [comment]
> 兼容模式启动

试过了，也不行

**Comment by insoxin** [comment]
> > 兼容模式启动
> 
> 试过了，也不行

![image](https://github.com/user-attachments/assets/3daa5c56-5179-416b-a7ad-ec4219984bde)
